name: 'Publish to Cloudflare Pages via POST'
description: 'Publish to Cloudflare Pages via a POST request using a deploy hook, using the GitHub Pages environment variables'
author: 'TheModdersDen'
inputs:
  url:
    description: 'The URL of the deploy hook'
    required: true
    default: CHANGEME
  shell:
    description: 'The shell to use to run the command'
    required: false
    default: bash
branding:
  icon: 'upload-cloud'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - name: 'Publish to Cloudflare Pages via POST'
      shell: ${{ inputs.shell }}
      run: |
        curl -X POST ${{ inputs.url }}
